### ISSUE TITLE
Member Count

### ISSUE THREAD

**Issue by HyperGaming99** [SilberGecko6917/ez-guild-search#2]
Wenn im Member Count ein , drin ist wegen über Tausend Member dann gib es einen fehler

**Comment by SilberGecko6917** [comment]
Heyy Kannst du Den Fehler Bitte hier reinsenden damit ich weiß wie ich den Fehler Reproduzieren kann?

**Comment by SilberGecko6917** [comment]
Es Sollte Jetzt Gefixt Sein!
